### ISSUE TITLE
multithread

### ISSUE THREAD

**Issue by Isaac94C** [bnoordhuis/libuv-chat#2]
I know someone already requested it.
But could you please add multithread support?

I have experience with libevent and multithreading.
Now i would like to compare it performance wise to Libuv.

Would be very kind.

Thanks in advance.

**Comment by bnoordhuis** [comment]
This repo is really just an example app that I use in talks that I give.  It's designed to be small and simple.  Adding threads would make it rather less so, never mind that I don't really have time to work on it.  Thanks for the suggestion, though!
